In [28]:
import numpy as np
import numpy.random as  rd
import pandas as pd

In [29]:
data=pd.read_csv('Employee_sales_data.csv')
data

,Unnamed: 0.25,Unnamed: 0.24,Unnamed: 0.23,Unnamed: 0.22,Unnamed: 0.21,Unnamed: 0.20,Unnamed: 0.19,Unnamed: 0.18,Unnamed: 0.17,Unnamed: 0.16,...,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Emp_ID,Emp_Name,SaleDate,SaleAmount
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,John Doe,10/26/2023 9:05,512.46
1,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,2,Jane Smith,4/22/2024 9:05,165.93
2,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,9,Grace Pink,2/13/2024 9:05,338.68
3,3,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,2,Jane Smith,2/2/2024 9:05,891.34
4,4,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,5,Carol White,11/5/2023 9:05,241.97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,95,95,95,95,95,95,95,95,95,...,95,95,95,95,95,95,3,Alice Johnson,11/10/2023 9:05,982.65
96,96,96,96,96,96,96,96,96,96,96,...,96,96,96,96,96,96,1,John Doe,10/11/2023 9:05,916.24
97,97,97,97,97,97,97,97,97,97,97,...,97,97,97,97,97,97,10,Henry Yellow,6/28/2024 9:05,696.70
98,98,98,98,98,98,98,98,98,98,98,...,98,98,98,98,98,98,7,Emma Green,12/17/2023 9:05,222.13
99,99,99,99,99,99,99,99,99,99,99,...,99,99,99,99,99,99,3,Alice Johnson,1/28/2024 9:05,145.26

In [30]:
df=pd.DataFrame(data)
df

,Unnamed: 0.25,Unnamed: 0.24,Unnamed: 0.23,Unnamed: 0.22,Unnamed: 0.21,Unnamed: 0.20,Unnamed: 0.19,Unnamed: 0.18,Unnamed: 0.17,Unnamed: 0.16,...,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Emp_ID,Emp_Name,SaleDate,SaleAmount
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,John Doe,10/26/2023 9:05,512.46
1,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,2,Jane Smith,4/22/2024 9:05,165.93
2,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,9,Grace Pink,2/13/2024 9:05,338.68
3,3,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,2,Jane Smith,2/2/2024 9:05,891.34
4,4,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,5,Carol White,11/5/2023 9:05,241.97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,95,95,95,95,95,95,95,95,95,...,95,95,95,95,95,95,3,Alice Johnson,11/10/2023 9:05,982.65
96,96,96,96,96,96,96,96,96,96,96,...,96,96,96,96,96,96,1,John Doe,10/11/2023 9:05,916.24
97,97,97,97,97,97,97,97,97,97,97,...,97,97,97,97,97,97,10,Henry Yellow,6/28/2024 9:05,696.70
98,98,98,98,98,98,98,98,98,98,98,...,98,98,98,98,98,98,7,Emma Green,12/17/2023 9:05,222.13
99,99,99,99,99,99,99,99,99,99,99,...,99,99,99,99,99,99,3,Alice Johnson,1/28/2024 9:05,145.26

In [31]:
df.to_csv('Employee_sales_data.csv')

In [32]:
df.duplicated().any()

np.False_

In [33]:
df.isnull().sum()

Unnamed: 0.25    0
Unnamed: 0.24    0
Unnamed: 0.23    0
Unnamed: 0.22    0
Unnamed: 0.21    0
Unnamed: 0.20    0
Unnamed: 0.19    0
Unnamed: 0.18    0
Unnamed: 0.17    0
Unnamed: 0.16    0
Unnamed: 0.15    0
Unnamed: 0.14    0
Unnamed: 0.13    0
Unnamed: 0.12    0
Unnamed: 0.11    0
Unnamed: 0.10    0
Unnamed: 0.9     0
Unnamed: 0.8     0
Unnamed: 0.7     0
Unnamed: 0.6     0
Unnamed: 0.5     0
Unnamed: 0.4     0
Unnamed: 0.3     0
Unnamed: 0.2     0
Unnamed: 0.1     0
Unnamed: 0       0
Emp_ID           0
Emp_Name         0
SaleDate         0
SaleAmount       0
dtype: int64

# Data Analysis

1. how many emp are present in our dataset

In [ ]:
Emp_ID.

NameError: name 'Emp_ID' is not defined