#importing the libraries

In [54]:
import pandas as pd
import numpy as np
import numpy.random as rd

In [55]:
d={'product_id':np.arange(100,106),
    'product_name':['Mobile','Laptop','Wireless_earphone','Tab','Wired_earphone','Tv'],
    'product_quantity':[20,10,None,12,50,30],
    'product_manf_date':['01-jan-2025','05-jun-2025','03/may/2025','07-feb-2025','01-jan-2025','02-sep-2025'],
    'product_amount':rd.randint(100,50000,6)
    }
print(d)
d

{'product_id': array([100, 101, 102, 103, 104, 105]), 'product_name': ['Mobile', 'Laptop', 'Wireless_earphone', 'Tab', 'Wired_earphone', 'Tv'], 'product_quantity': [20, 10, None, 12, 50, 30], 'product_manf_date': ['01-jan-2025', '05-jun-2025', '03/may/2025', '07-feb-2025', '01-jan-2025', '02-sep-2025'], 'product_amount': array([42632, 30052, 32210,  8624, 20721, 30828], dtype=int32)}

{'product_id': array([100, 101, 102, 103, 104, 105]),
 'product_name': ['Mobile',
  'Laptop',
  'Wireless_earphone',
  'Tab',
  'Wired_earphone',
  'Tv'],
 'product_quantity': [20, 10, None, 12, 50, 30],
 'product_manf_date': ['01-jan-2025',
  '05-jun-2025',
  '03/may/2025',
  '07-feb-2025',
  '01-jan-2025',
  '02-sep-2025'],
 'product_amount': array([42632, 30052, 32210,  8624, 20721, 30828], dtype=int32)}

In [56]:
# excel viewer

In [57]:
(pd.DataFrame(d))#it convert dict data set to table formate

,product_id,product_name,product_quantity,product_manf_date,product_amount
0,100,Mobile,20.0,01-jan-2025,42632
1,101,Laptop,10.0,05-jun-2025,30052
2,102,Wireless_earphone,NaN,03/may/2025,32210
3,103,Tab,12.0,07-feb-2025,8624
4,104,Wired_earphone,50.0,01-jan-2025,20721
5,105,Tv,30.0,02-sep-2025,30828

In [58]:
df=pd.DataFrame(d)
df

,product_id,product_name,product_quantity,product_manf_date,product_amount
0,100,Mobile,20.0,01-jan-2025,42632
1,101,Laptop,10.0,05-jun-2025,30052
2,102,Wireless_earphone,NaN,03/may/2025,32210
3,103,Tab,12.0,07-feb-2025,8624
4,104,Wired_earphone,50.0,01-jan-2025,20721
5,105,Tv,30.0,02-sep-2025,30828

In [59]:
df.to_csv('products.csv')#
df.to_excel('products.xlsx')

get the top 5 rows

In [60]:
df.head()

,product_id,product_name,product_quantity,product_manf_date,product_amount
0,100,Mobile,20.0,01-jan-2025,42632
1,101,Laptop,10.0,05-jun-2025,30052
2,102,Wireless_earphone,NaN,03/may/2025,32210
3,103,Tab,12.0,07-feb-2025,8624
4,104,Wired_earphone,50.0,01-jan-2025,20721

get top 2 rows

In [61]:
df.head(2)

   product_id product_name  product_quantity product_manf_date  product_amount
0         100       Mobile              20.0       01-jan-2025           42632
1         101       Laptop              10.0       05-jun-2025           30052

get the botto 5 rows

In [62]:
df.tail()# the default number of rows is 5

,product_id,product_name,product_quantity,product_manf_date,product_amount
1,101,Laptop,10.0,05-jun-2025,30052
2,102,Wireless_earphone,NaN,03/may/2025,32210
3,103,Tab,12.0,07-feb-2025,8624
4,104,Wired_earphone,50.0,01-jan-2025,20721
5,105,Tv,30.0,02-sep-2025,30828

get the bottom 3 rows

In [63]:
df.tail(3)

,product_id,product_name,product_quantity,product_manf_date,product_amount
3,103,Tab,12.0,07-feb-2025,8624
4,104,Wired_earphone,50.0,01-jan-2025,20721
5,105,Tv,30.0,02-sep-2025,30828

get the 4 rth row

In [64]:
df.loc[4]

product_id                      104
product_name         Wired_earphone
product_quantity               50.0
product_manf_date       01-jan-2025
product_amount                20721
Name: 4, dtype: object

get the 4rth  row product name

In [65]:
df.loc[4,'product_name']

'Wired_earphone'

get the all the products_names

In [66]:
df.loc[::,'product_name']#before the ,(comma) column based,after (comma) row based
#-----------------or
df['product_name']

0               Mobile
1               Laptop
2    Wireless_earphone
3                  Tab
4       Wired_earphone
5                   Tv
Name: product_name, dtype: object

get the product_name and amount of 1st and 5th row

In [67]:
df.loc[[1,5],['product_name','product_amount']]

  product_name  product_amount
1       Laptop           30052
5           Tv           30828

get the laptop information

In [68]:
a=df['product_name']=='Laptop'
a               #a holds bool_values
#df.loc[a]        #select only true values

0    False
1     True
2    False
3    False
4    False
5    False
Name: product_name, dtype: bool

In [69]:
df.loc[df['product_name']=='Laptop']#1 row all col
df.loc[1:5,['product_amount','product_id']]#5 rows and 2 col

   product_amount  product_id
1           30052         101
2           32210         102
3            8624         103
4           20721         104
5           30828         105

In [70]:
df['product_quantity'].fillna(0)#its not permanent,it will replace the nan values to other values
df['product_quantity']=df['product_quantity'].fillna(0)#inplace of nan it will give 0.0
df

,product_id,product_name,product_quantity,product_manf_date,product_amount
0,100,Mobile,20.0,01-jan-2025,42632
1,101,Laptop,10.0,05-jun-2025,30052
2,102,Wireless_earphone,0.0,03/may/2025,32210
3,103,Tab,12.0,07-feb-2025,8624
4,104,Wired_earphone,50.0,01-jan-2025,20721
5,105,Tv,30.0,02-sep-2025,30828

In [71]:
df['discount_flat']=[50]*6# adding newcol
df

,product_id,product_name,product_quantity,product_manf_date,product_amount,discount_flat
0,100,Mobile,20.0,01-jan-2025,42632,50
1,101,Laptop,10.0,05-jun-2025,30052,50
2,102,Wireless_earphone,0.0,03/may/2025,32210,50
3,103,Tab,12.0,07-feb-2025,8624,50
4,104,Wired_earphone,50.0,01-jan-2025,20721,50
5,105,Tv,30.0,02-sep-2025,30828,50

#creating new column (discount)

In [72]:
# df['discount_flat']=rd.randint(50,60,6)
# df

In [73]:
# df.loc[-1,::]=None
df.loc[len(df),::]=[100.0,'Mobile',20.0,'01-jan-2025',27800.0,59.0]
df

,product_id,product_name,product_quantity,product_manf_date,product_amount,discount_flat
0,100.0,Mobile,20.0,01-jan-2025,42632.0,50.0
1,101.0,Laptop,10.0,05-jun-2025,30052.0,50.0
2,102.0,Wireless_earphone,0.0,03/may/2025,32210.0,50.0
3,103.0,Tab,12.0,07-feb-2025,8624.0,50.0
4,104.0,Wired_earphone,50.0,01-jan-2025,20721.0,50.0
5,105.0,Tv,30.0,02-sep-2025,30828.0,50.0
6,100.0,Mobile,20.0,01-jan-2025,27800.0,59.0

In [74]:
len(df)

7

In [75]:
df.loc[1:5:]

,product_id,product_name,product_quantity,product_manf_date,product_amount,discount_flat
1,101.0,Laptop,10.0,05-jun-2025,30052.0,50.0
2,102.0,Wireless_earphone,0.0,03/may/2025,32210.0,50.0
3,103.0,Tab,12.0,07-feb-2025,8624.0,50.0
4,104.0,Wired_earphone,50.0,01-jan-2025,20721.0,50.0
5,105.0,Tv,30.0,02-sep-2025,30828.0,50.0

In [76]:
df.loc[len(df),::]=[100.0,'Mobile',20.0,'01-jan-2025',14488.0,50.0]
df

,product_id,product_name,product_quantity,product_manf_date,product_amount,discount_flat
0,100.0,Mobile,20.0,01-jan-2025,42632.0,50.0
1,101.0,Laptop,10.0,05-jun-2025,30052.0,50.0
2,102.0,Wireless_earphone,0.0,03/may/2025,32210.0,50.0
3,103.0,Tab,12.0,07-feb-2025,8624.0,50.0
4,104.0,Wired_earphone,50.0,01-jan-2025,20721.0,50.0
5,105.0,Tv,30.0,02-sep-2025,30828.0,50.0
6,100.0,Mobile,20.0,01-jan-2025,27800.0,59.0
7,100.0,Mobile,20.0,01-jan-2025,14488.0,50.0

In [77]:
len(df)

8

In [78]:
df['product_quantity'].astype(int)

0    20
1    10
2     0
3    12
4    50
5    30
6    20
7    20
Name: product_quantity, dtype: int64

In [79]:
df.columns

Index(['product_id', 'product_name', 'product_quantity', 'product_manf_date',
       'product_amount', 'discount_flat'],
      dtype='object')

In [80]:
df=df.astype({'product_id':int,'product_quantity':int,'product_amount':int,'discount_flat':int})
df

,product_id,product_name,product_quantity,product_manf_date,product_amount,discount_flat
0,100,Mobile,20,01-jan-2025,42632,50
1,101,Laptop,10,05-jun-2025,30052,50
2,102,Wireless_earphone,0,03/may/2025,32210,50
3,103,Tab,12,07-feb-2025,8624,50
4,104,Wired_earphone,50,01-jan-2025,20721,50
5,105,Tv,30,02-sep-2025,30828,50
6,100,Mobile,20,01-jan-2025,27800,59
7,100,Mobile,20,01-jan-2025,14488,50

In [81]:
df[['made_in','availability']]=[['india',1],['china',0],['india',1],['china',0],['india',1],['china',0],['japan',1],['japan',1]]
df
# df[['made_in','availability']]=[['india',1]]*8

,product_id,product_name,product_quantity,product_manf_date,product_amount,discount_flat,made_in,availability
0,100,Mobile,20,01-jan-2025,42632,50,india,1
1,101,Laptop,10,05-jun-2025,30052,50,china,0
2,102,Wireless_earphone,0,03/may/2025,32210,50,india,1
3,103,Tab,12,07-feb-2025,8624,50,china,0
4,104,Wired_earphone,50,01-jan-2025,20721,50,india,1
5,105,Tv,30,02-sep-2025,30828,50,china,0
6,100,Mobile,20,01-jan-2025,27800,59,japan,1
7,100,Mobile,20,01-jan-2025,14488,50,japan,1

In [82]:
df.duplicated().any()# it will check duplicates

np.False_

In [83]:
df=df.drop_duplicates(keep='first')
df

,product_id,product_name,product_quantity,product_manf_date,product_amount,discount_flat,made_in,availability
0,100,Mobile,20,01-jan-2025,42632,50,india,1
1,101,Laptop,10,05-jun-2025,30052,50,china,0
2,102,Wireless_earphone,0,03/may/2025,32210,50,india,1
3,103,Tab,12,07-feb-2025,8624,50,china,0
4,104,Wired_earphone,50,01-jan-2025,20721,50,india,1
5,105,Tv,30,02-sep-2025,30828,50,china,0
6,100,Mobile,20,01-jan-2025,27800,59,japan,1
7,100,Mobile,20,01-jan-2025,14488,50,japan,1

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   product_id         8 non-null      int64
 1   product_name       8 non-null      object
 2   product_quantity   8 non-null      int64
 3   product_manf_date  8 non-null      object
 4   product_amount     8 non-null      int64
 5   discount_flat      8 non-null      int64
 6   made_in            8 non-null      object
 7   availability       8 non-null      object
dtypes: int64(4), object(4)
memory usage: 644.0+ bytes

In [85]:
df['made_in']=df['made_in'].str.title()
df
df['product_name']=df['product_name'].str.title()
df

,product_id,product_name,product_quantity,product_manf_date,product_amount,discount_flat,made_in,availability
0,100,Mobile,20,01-jan-2025,42632,50,India,1
1,101,Laptop,10,05-jun-2025,30052,50,China,0
2,102,Wireless_Earphone,0,03/may/2025,32210,50,India,1
3,103,Tab,12,07-feb-2025,8624,50,China,0
4,104,Wired_Earphone,50,01-jan-2025,20721,50,India,1
5,105,Tv,30,02-sep-2025,30828,50,China,0
6,100,Mobile,20,01-jan-2025,27800,59,Japan,1
7,100,Mobile,20,01-jan-2025,14488,50,Japan,1

In [86]:
df['made_in'].nunique()

3

In [87]:
df['made_in'].unique()

array(['India', 'China', 'Japan'], dtype=object)

In [88]:
df['made_in'].mode()

0    China
1    India
Name: made_in, dtype: object

In [89]:
df['made_in'].mode()[1]

'India'

In [90]:
df['made_in'].value_counts()

made_in
India    3
China    3
Japan    2
Name: count, dtype: int64

In [91]:
#df.drop(columns=['discount_flat','availability']),temperory storing
df=df.drop(columns=['discount_flat','availability'])#permanent storing,it can remove the given col
df    #it will remove col

,product_id,product_name,product_quantity,product_manf_date,product_amount,made_in
0,100,Mobile,20,01-jan-2025,42632,India
1,101,Laptop,10,05-jun-2025,30052,China
2,102,Wireless_Earphone,0,03/may/2025,32210,India
3,103,Tab,12,07-feb-2025,8624,China
4,104,Wired_Earphone,50,01-jan-2025,20721,India
5,105,Tv,30,02-sep-2025,30828,China
6,100,Mobile,20,01-jan-2025,27800,Japan
7,100,Mobile,20,01-jan-2025,14488,Japan

In [92]:
#df.drop(index=[0,2,4]),if ur getting tempory col store  table name with col name as a variable
df=df.drop(index=[0,2,4,6])# if u r getting table temporory store table name as variable
df    # it will remove row

,product_id,product_name,product_quantity,product_manf_date,product_amount,made_in
1,101,Laptop,10,05-jun-2025,30052,China
3,103,Tab,12,07-feb-2025,8624,China
5,105,Tv,30,02-sep-2025,30828,China
7,100,Mobile,20,01-jan-2025,14488,Japan

In [93]:
df.reset_index()# by default false that means don't drop the table keep it as a col

,index,product_id,product_name,product_quantity,product_manf_date,product_amount,made_in
0,1,101,Laptop,10,05-jun-2025,30052,China
1,3,103,Tab,12,07-feb-2025,8624,China
2,5,105,Tv,30,02-sep-2025,30828,China
3,7,100,Mobile,20,01-jan-2025,14488,Japan

In [94]:
#df.reset_index(drop=True),temperory
df=df.reset_index(drop=True)# permanent
df

,product_id,product_name,product_quantity,product_manf_date,product_amount,made_in
0,101,Laptop,10,05-jun-2025,30052,China
1,103,Tab,12,07-feb-2025,8624,China
2,105,Tv,30,02-sep-2025,30828,China
3,100,Mobile,20,01-jan-2025,14488,Japan

In [95]:
df['availability']=[0,None,1,None]
df

,product_id,product_name,product_quantity,product_manf_date,product_amount,made_in,availability
0,101,Laptop,10,05-jun-2025,30052,China,0.0
1,103,Tab,12,07-feb-2025,8624,China,NaN
2,105,Tv,30,02-sep-2025,30828,China,1.0
3,100,Mobile,20,01-jan-2025,14488,Japan,NaN

In [96]:
df.dropna(axis=0)

,product_id,product_name,product_quantity,product_manf_date,product_amount,made_in,availability
0,101,Laptop,10,05-jun-2025,30052,China,0.0
2,105,Tv,30,02-sep-2025,30828,China,1.0

In [97]:
# df.dropna(axis=1)
# df=df.dropna(axis=1),#permanent
# df

In [98]:
df.replace({'China':'india','Japan':'UK'})# it will check all the col

,product_id,product_name,product_quantity,product_manf_date,product_amount,made_in,availability
0,101,Laptop,10,05-jun-2025,30052,india,0.0
1,103,Tab,12,07-feb-2025,8624,india,NaN
2,105,Tv,30,02-sep-2025,30828,india,1.0
3,100,Mobile,20,01-jan-2025,14488,UK,NaN

In [99]:
df['made_in']=df['made_in'].replace({'China':'india','Japan':'UK'})# it will check only perticular col
df

,product_id,product_name,product_quantity,product_manf_date,product_amount,made_in,availability
0,101,Laptop,10,05-jun-2025,30052,india,0.0
1,103,Tab,12,07-feb-2025,8624,india,NaN
2,105,Tv,30,02-sep-2025,30828,india,1.0
3,100,Mobile,20,01-jan-2025,14488,UK,NaN

In [100]:
df.to_csv('prod.csv')

In [101]:
x=df['made_in'].value_counts()#india and uk is index ,3 and 1 are values
#values_counts()returns--->index and values

In [102]:
x.index#it holds the column which is used for grouping

Index(['india', 'UK'], dtype='object', name='made_in')

In [103]:
x.values#it the holds the aggrigation(count)

array([3, 1])

In [ ]:
x==1#one index and one col

made_in
india    False
UK        True
Name: count, dtype: bool

In [105]:
x[x==1]

made_in
UK    1
Name: count, dtype: int64

In [107]:
x[x==1].index

Index(['UK'], dtype='object', name='made_in')

In [108]:
x[x==1].values

array([1])